### ISSUE TITLE
Fails to add fake receipt if latest transaction is from a pot

### ISSUE THREAD

**Issue by bonzi** [monzo/reference-receipts-app#1]
When trying the reference code, If your most recent transaction is from a pot, it crashes complaining about privileges

`Error: Failed to upload receipt: {'code': 'forbidden.insufficient_permissions', 'message': 'Access forbidden due to insufficient permissions', 'params': {'client_id': 'oauth2client_xxxxxx', 'user_id': 'user_xxxxxxxl'}}`

**Comment by icydoge2** [comment]
Should be fixed in #2, apologies for the long delay.
